/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-09-01 09:40:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class gzwdc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<link href=\"css/jquery.bootgrid.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"js/jquery.bootgrid.min.js\"></script>\r\n");
      out.write("     <!--Start Breadcrumb-->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div id=\"breadcrumb\" class=\"col-xs-12\">\r\n");
      out.write("\t\t<ol class=\"breadcrumb pull-left\">\r\n");
      out.write("\t\t\t<li><a href=\"index\">首页</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">不动产权籍调查</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">构(建)筑物调查表</a></li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>       \r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                       <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"box ui-draggable ui-droppable\">\r\n");
      out.write("\t\t\t\t<div class=\"box-header\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box-name\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-coffee\"></i> <span>构(建)筑物调查表</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"box-icons\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-link\"> <i class=\"fa fa-chevron-up\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a> <a class=\"expand-link\"> <i class=\"fa fa-expand\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a> <a class=\"close-link\"> <i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"no-move\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"box-content\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"addinfo\" class=\"btn btn-info\">添加新记录</button>\r\n");
      out.write("                                <table id=\"grid-data\" class=\"table table-striped table-hover table-heading table-datatable\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t            <tr>\r\n");
      out.write("\t\t\t\t\t\t\t                <th data-column-id=\"id\" data-type=\"numeric\">id</th>\r\n");
      out.write("\t\t\t\t\t\t\t                <th data-column-id=\"zddm\">宗地（海）代码</th>\r\n");
      out.write("\t\t\t\t\t\t\t                <th data-column-id=\"zl\">坐落</th>\r\n");
      out.write("\t\t\t\t\t\t\t                <th data-column-id=\"bdcdyh\">不动产单元号</th>\r\n");
      out.write("\t\t\t\t\t\t\t                <th data-column-id=\"gzwsyqr\">构（建）筑物所有权人</th>\r\n");
      out.write("\t\t\t\t\t\t\t                <th data-column-id=\"commands\" data-formatter=\"commands\">操作</th>\r\n");
      out.write("\t\t\t\t\t\t\t            </tr>\r\n");
      out.write("\t\t\t\t\t\t\t        </thead>\r\n");
      out.write("\t\t\t\t\t\t\t    </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6 col-md-offset-3\">\r\n");
      out.write("                    <div id=\"inputbox\" class=\"box ui-draggable ui-droppable\">\r\n");
      out.write("\t\t\t\t<div class=\"box-header\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box-name\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-coffee\"></i> <span>新建构(建)筑物调查表</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"box-icons\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-link\"> <i class=\"fa fa-chevron-up\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a> <a class=\"expand-link\"> <i class=\"fa fa-expand\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a> <a class=\"close-link\"> <i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"no-move\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"box-content\">\r\n");
      out.write("\t\t\t\t\t<div class=Section1 style='layout-grid:15.6pt'>\r\n");
      out.write("<form action=\"\" method=\"post\" id=\"gzwdc\">\r\n");
      out.write("<table class=MsoNormalTable border=1 cellspacing=0 cellpadding=0\r\n");
      out.write(" style='margin-left:2.85pt;border-collapse:collapse;border:none;mso-border-alt:\r\n");
      out.write(" solid windowtext .5pt;mso-padding-alt:0cm 2.85pt 0cm 2.85pt;mso-border-insideh:\r\n");
      out.write(" .5pt solid windowtext;mso-border-insidev:.5pt solid windowtext'>\r\n");
      out.write(" <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;page-break-inside:avoid;\r\n");
      out.write("  height:34.6pt'>\r\n");
      out.write("  <td width=605 colspan=4 style='width:16.0cm;border:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 2.85pt 0cm 2.85pt;\r\n");
      out.write("  height:34.6pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;mso-line-height-alt:12.0pt;text-autospace:none'><b\r\n");
      out.write("  style='mso-bidi-font-weight:normal'><span style='font-size:15.0pt;font-family:\r\n");
      out.write("  仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\"Times New Roman\";\r\n");
      out.write("  mso-bidi-font-family:\"Times New Roman\"'>构（建）筑物调查表</span></b><b\r\n");
      out.write("  style='mso-bidi-font-weight:normal'><span lang=EN-US style='font-size:15.0pt;\r\n");
      out.write("  font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></b></p>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:1;height:31.1pt'>\r\n");
      out.write("  <td width=144 style='width:107.8pt;border:solid windowtext 1.0pt;border-top:\r\n");
      out.write("  none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:31.1pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>宗地（海）代码</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=160 style='width:120.25pt;border-top:none;border-left:none;\r\n");
      out.write("  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 0 0cm 0;height:31.1pt'>\r\n");
      out.write("  <input type=\"text\" name=\"zddm\" id=\"zddm\" width=\"100%\">\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=83 style='width:62.25pt;border-top:none;border-left:none;\r\n");
      out.write("  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0;height:31.1pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>坐落</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=218 valign=bottom style='width:163.3pt;border-top:none;border-left:\r\n");
      out.write("  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:31.1pt'>\r\n");
      out.write("  <input type=\"text\" name=\"zl\" id=\"zl\">\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:2;height:31.25pt'>\r\n");
      out.write("  <td width=144 style='width:107.8pt;border:solid windowtext 1.0pt;border-top:\r\n");
      out.write("  none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:31.25pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>不动产单元号</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=461 colspan=3 style='width:345.8pt;border-top:none;border-left:\r\n");
      out.write("  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:31.25pt'>\r\n");
      out.write("  <input type=\"text\" name=\"bdcdyh\" id=\"bdcdyh\"   >\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:3;height:21.05pt'>\r\n");
      out.write("  <td width=144 rowspan=2 style='width:107.8pt;border:solid windowtext 1.0pt;\r\n");
      out.write("  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:21.05pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>构（建）筑物</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><span\r\n");
      out.write("  style='mso-spacerun:yes'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span\r\n");
      out.write("  style='font-size:10.5pt;font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";\r\n");
      out.write("  mso-hansi-font-family:\"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>所有权人</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=160 rowspan=2 valign=top style='width:120.25pt;border-top:none;\r\n");
      out.write("  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:21.05pt'>\r\n");
      out.write("  <input type=\"text\" name=\"gzwsyqr\" id=\"gzwsyqr\">\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=83 style='width:62.25pt;border-top:none;border-left:none;\r\n");
      out.write("  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:21.05pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>证件种类</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=218 valign=top style='width:163.3pt;border-top:none;border-left:\r\n");
      out.write("  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:21.05pt'>\r\n");
      out.write("  <input type=\"text\" name=\"zjzl\" id=\"zjzl\">\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:4;height:21.45pt'>\r\n");
      out.write("  <td width=83 style='width:62.25pt;border-top:none;border-left:none;\r\n");
      out.write("  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:21.45pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>证件号</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=218 valign=top style='width:163.3pt;border-top:none;border-left:\r\n");
      out.write("  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:21.45pt'>\r\n");
      out.write("  <input type=\"text\" name=\"zjh\" id=\"zjh\">\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:5;height:26.65pt'>\r\n");
      out.write("  <td width=144 style='width:107.8pt;border:solid windowtext 1.0pt;border-top:\r\n");
      out.write("  none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:26.65pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>权利人类型</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=461 colspan=3 valign=top style='width:345.8pt;border-top:none;\r\n");
      out.write("  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:26.65pt'>\r\n");
      out.write("  <input type=\"text\" name=\"qlrlx\" id=\"qlrlx\">\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:6;height:28.3pt'>\r\n");
      out.write("  <td width=144 style='width:107.8pt;border:solid windowtext 1.0pt;border-top:\r\n");
      out.write("  none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:28.3pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>构（建）筑物</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>类型</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=461 colspan=3 valign=top style='width:345.8pt;border-top:none;\r\n");
      out.write("  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:28.3pt'>\r\n");
      out.write("  <input type=\"text\" name=\"gzwlx\" id=\"gzwlx\">\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:7;height:28.1pt'>\r\n");
      out.write("  <td width=144 style='width:107.8pt;border:solid windowtext 1.0pt;border-top:\r\n");
      out.write("  none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:28.1pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>构（建）筑物</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>规划用途</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=461 colspan=3 valign=top style='width:345.8pt;border-top:none;\r\n");
      out.write("  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:28.1pt'>\r\n");
      out.write("  <input type=\"text\" name=\"gzwghyt\" id=\"gzwghyt\">\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:8;height:27.85pt'>\r\n");
      out.write("  <td width=144 style='width:107.8pt;border:solid windowtext 1.0pt;border-top:\r\n");
      out.write("  none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:27.85pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>构（建）筑物</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>面积（</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'>m<sup>2</sup></span><span\r\n");
      out.write("  style='font-size:10.5pt;font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";\r\n");
      out.write("  mso-hansi-font-family:\"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>）</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=461 colspan=3 valign=top style='width:345.8pt;border-top:none;\r\n");
      out.write("  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:27.85pt'>\r\n");
      out.write("  <input type=\"text\" name=\"gzwmj\" id=\"gzwmj\">\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:9;height:27.55pt'>\r\n");
      out.write("  <td width=144 style='width:107.8pt;border:solid windowtext 1.0pt;border-top:\r\n");
      out.write("  none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:27.55pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>竣工时间</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=461 colspan=3 valign=top style='width:345.8pt;border-top:none;\r\n");
      out.write("  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:27.55pt'>\r\n");
      out.write("\t<input type=\"text\" name=\"jgsj\" id=\"jgsj\">\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:10;height:27.55pt'>\r\n");
      out.write("  <td width=144 style='width:107.8pt;border:solid windowtext 1.0pt;border-top:\r\n");
      out.write("  none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:27.55pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>共有情况</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=461 colspan=3 valign=top style='width:345.8pt;border-top:none;\r\n");
      out.write("  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:27.55pt'>\r\n");
      out.write("  <input type=\"text\" name=\"gyqk\" id=\"gyqk\">\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:11;height:27.55pt'>\r\n");
      out.write("  <td width=144 style='width:107.8pt;border:solid windowtext 1.0pt;border-top:\r\n");
      out.write("  none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:27.55pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>备注</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write("  <td width=461 colspan=3 valign=top style='width:345.8pt;border-top:none;\r\n");
      out.write("  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\r\n");
      out.write("  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;\r\n");
      out.write("  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:27.55pt'>\r\n");
      out.write("  <input type=\"text\" name=\"bz\" id=\"bz\">\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr style='mso-yfti-irow:12;mso-yfti-lastrow:yes;height:302.9pt'>\r\n");
      out.write("  <td width=605 colspan=4 style='width:16.0cm;border:solid windowtext 1.0pt;\r\n");
      out.write("  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;\r\n");
      out.write("  padding:0cm 5.4pt 0cm 5.4pt;height:302.9pt'>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>附图</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span style='font-size:10.5pt;\r\n");
      out.write("  font-family:仿宋;mso-ascii-font-family:\"Times New Roman\";mso-hansi-font-family:\r\n");
      out.write("  \"Times New Roman\";mso-bidi-font-family:\"Times New Roman\"'>（构（建）筑物平面图，可附页）</span><span\r\n");
      out.write("  lang=EN-US style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p></o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  <p class=MsoNormal align=center style='text-align:center;text-indent:0cm;\r\n");
      out.write("  mso-char-indent-count:0;line-height:12.0pt'><span lang=EN-US\r\n");
      out.write("  style='font-size:10.5pt;font-family:\"Times New Roman\",\"serif\"'><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<input type=\"hidden\" name=\"id\" id=\"myid\">\r\n");
      out.write("</form>\r\n");
      out.write("<p class=MsoNormal style='text-indent:28.0pt'><span lang=EN-US><o:p>&nbsp;</o:p></span></p>\r\n");
      out.write("\t<button type=\"button\" id=\"add\" class=\"btn btn-info\">新增</button>\r\n");
      out.write("\t<button type=\"button\" id=\"update\" class=\"btn btn-info\">保存修改</button>\r\n");
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("$(\"#add\").hide(); $(\"#update\").hide();$(\"#inputbox\").hide();\r\n");
      out.write("  $(\"#addinfo\").click(function(){\r\n");
      out.write("    $(\"#add\").show();\r\n");
      out.write("    $(\"#inputbox\").show();$(\"#update\").hide();\r\n");
      out.write("    $(\"form\")[0].reset();\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  $(\"#update\").click(function(){\r\n");
      out.write("  \t\t$.post(\"updategzwdc\",$(\"form\").serialize(),function(){\r\n");
      out.write("  \t\talert(\"修改成功\");\r\n");
      out.write("\t\tLoadAjaxContent(\"gzwdc\");\r\n");
      out.write("  \t});\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  $(\"#add\").click(function(){\r\n");
      out.write("  \t$.post(\"insertgzwdc\",$(\"form\").serialize(),function(){\r\n");
      out.write("  \t\talert(\"添加成功\");\r\n");
      out.write("\t\tLoadAjaxContent(\"gzwdc\");\r\n");
      out.write("  \t});\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  $('#jgsj').datepicker({setDate: new Date(), dateFormat: 'yy-mm-dd'});\r\n");
      out.write("  \r\n");
      out.write("  var grid = $(\"#grid-data\").bootgrid({\r\n");
      out.write("  \tnavigation:2,\r\n");
      out.write("  \tcolumnSelection:false,\r\n");
      out.write("    ajax: true,\r\n");
      out.write("    url: \"getgzwdc\",\r\n");
      out.write("    formatters: {\r\n");
      out.write("        \"commands\": function(column, row)\r\n");
      out.write("        {\r\n");
      out.write("            return \"<button type=\\\"button\\\" class=\\\"btn btn-xs btn-info command-edit\\\" data-row-id=\\\"\" + row.id + \"\\\">修改</button> \" + \r\n");
      out.write("                \"<button type=\\\"button\\\" class=\\\"btn btn-xs btn-info command-delete\\\" data-row-id=\\\"\" + row.id + \"\\\">删除</button>\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}).on(\"loaded.rs.jquery.bootgrid\", function()\r\n");
      out.write("{\r\n");
      out.write("    /* Executes after data is loaded and rendered */\r\n");
      out.write("    grid.find(\".command-edit\").on(\"click\", function(e)\r\n");
      out.write("    {\r\n");
      out.write("        $(\"#update\").show();\r\n");
      out.write("        $(\"#add\").hide();$(\"#inputbox\").show();\r\n");
      out.write("        $.post(\"getinfobyid\",{id:$(this).data(\"row-id\")},function(d){\r\n");
      out.write("        \t$(\"#zddm\").val(d.zddm);\r\n");
      out.write("        \t$(\"#zl\").val(d.zl);\r\n");
      out.write("        \t$(\"#bdcdyh\").val(d.bdcdyh);\r\n");
      out.write("        \t$(\"#gzwsyqr\").val(d.gzwsyqr);\r\n");
      out.write("        \t$(\"#zjzl\").val(d.zjzl);\r\n");
      out.write("        \t$(\"#zjh\").val(d.zjh);\r\n");
      out.write("        \t$(\"#qlrlx\").val(d.qlrlx);\r\n");
      out.write("        \t$(\"#gzwlx\").val(d.gzwlx);\r\n");
      out.write("        \t$(\"#gzwghyt\").val(d.gzwghyt);\r\n");
      out.write("        \t$(\"#gzwmj\").val(d.gzwmj);\r\n");
      out.write("        \t$(\"#jgsj\").val(d.jgsj);\r\n");
      out.write("        \t$(\"#gyqk\").val(d.gyqk);\r\n");
      out.write("        \t$(\"#bz\").val(d.bz);\r\n");
      out.write("        \t$(\"#myid\").val(d.id);\r\n");
      out.write("        });\r\n");
      out.write("    }).end().find(\".command-delete\").on(\"click\", function(e)\r\n");
      out.write("    {\r\n");
      out.write("        $.post(\"deletegzwdc\",{id:$(this).data(\"row-id\")},function(){\r\n");
      out.write("        \talert(\"删除成功\");\r\n");
      out.write("        \tLoadAjaxContent(\"gzwdc\");\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("  \r\n");
      out.write("}); \t\r\n");
      out.write("</script>            \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
